Traceback (most recent call last):
  File "D_fake.py", line 26, in <module>
    img_fake = np.array(img_fake, dtype=np.float32)
ValueError: setting an array element with a sequence.
